use crate::model::{Category, Severity};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scope {
    /// Any inventoried file.
    Any,
    /// Source code (excludes YAML/JSON/config/docs).
    Code,
    /// Migration and schema files.
    Migration,
    /// Frontend sources.
    Frontend,
    /// Infrastructure, container and reverse-proxy config.
    Infra,
    /// Config-ish files, including YAML/TOML/INI/env. Part of the rule schema;
    /// no shipped rule needs it yet, contributed rules may.
    #[allow(dead_code)]
    Config,
}

#[derive(Debug, Clone, Copy)]
pub struct Rule {
    pub id: &'static str,
    pub category: Category,
    pub severity: Severity,
    pub title: &'static str,
    pub description: &'static str,
    pub impact: &'static str,
    pub remediation: &'static str,
    pub pattern: &'static str,
    /// When this also matches, the hit is discarded (false-positive guard).
    pub negate: Option<&'static str>,
    pub languages: &'static [&'static str],
    pub scope: Scope,
    pub skip_tests: bool,
    pub cwe: Option<u32>,
    pub asvs: &'static [&'static str],
    pub policy: &'static [&'static str],
}

const PLACEHOLDER_GUARD: &str = r"(?i)(example|sample|dummy|placeholder|changeme|change_me|your[_-]?|xxx|todo|fake|test[_-]?only|synthetic|redacted|\{\{|\$\{|<[a-z_]+>|os\.environ|os\.getenv|getenv|process\.env|System\.getenv|dotenv|secretsmanager|vault|\bENV\[)";

pub const RULES: &[Rule] = &[
    Rule {
        id: "DB-SEC-001",
        category: Category::Secrets,
        severity: Severity::Critical,
        title: "Password Or Key Written Directly Into The Code",
        description: "A password, key or token is stored as a literal in the source.",
        impact: "Anyone with access to the repository — a former employee, a contractor, the owner of a fork — obtains this value. Removing it from git history afterwards is practically impossible.",
        remediation: "Move the value to an environment variable or an encrypted secret store, and rotate the existing value: history is forever.",
        pattern: r#"(?i)\b(password|passwd|pwd|secret|api[_-]?key|apikey|access[_-]?token|auth[_-]?token|client[_-]?secret|private[_-]?key|encryption[_-]?key|signing[_-]?key|jwt[_-]?secret)\s*[:=]\s*["'][^"']{8,}["']"#,
        negate: Some(PLACEHOLDER_GUARD),
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(798),
        asvs: &["V2.10.4", "V14.3.3"],
        policy: &["SEC-03, b.3.1/1"],
    },
    Rule {
        id: "DB-SEC-002",
        category: Category::Secrets,
        severity: Severity::Critical,
        title: "Private Encryption Key Committed To The Repository",
        description: "A PEM private key or an age private key has been committed.",
        impact: "Whoever holds the key can read encrypted traffic, forge signatures or log in to the server.",
        remediation: "Remove the key, revoke it immediately and issue a new one. Adding it to .gitignore is not enough.",
        pattern: r"-----BEGIN [A-Z ]*PRIVATE KEY-----|AGE-SECRET-KEY-1[0-9A-Z]{20,}",
        negate: Some(r#"-----BEGIN [A-Z ]*PRIVATE KEY-----[A-Za-z0-9+/=]{0,8}["'`]"#),
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(798),
        asvs: &["V6.4.1"],
        policy: &["SEC-03, b.3.1/1"],
    },
    Rule {
        id: "DB-SEC-003",
        category: Category::Secrets,
        severity: Severity::Critical,
        title: "Third-Party API Key Visible In The Code",
        description: "A value matching a known cloud or payment provider key format was found.",
        impact: "These keys grant direct access to your account: cloud resources, payment operations, outbound email.",
        remediation: "Revoke the key in the provider console right away, issue a new one and review its usage log.",
        pattern: r"\bAKIA[0-9A-Z]{16}\b|\b(?:sk|rk)_live_[A-Za-z0-9]{16,}|\bgh[pousr]_[A-Za-z0-9]{30,}|\bglpat-[A-Za-z0-9_\-]{16,}|\bxox[baprs]-[A-Za-z0-9\-]{10,}|\bAIza[0-9A-Za-z_\-]{30,}",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(798),
        asvs: &["V2.10.4"],
        policy: &["SEC-03, b.3.1/1"],
    },
    Rule {
        id: "DB-SEC-004",
        category: Category::Secrets,
        severity: Severity::High,
        title: "Database Connection String Contains A Cleartext Password",
        description: "A database or service connection string carries the password in the clear.",
        impact: "It grants full database access, and it is repeated in logs and error messages.",
        remediation: "Separate the password from the connection string and read it from an environment variable.",
        pattern: r"(?i)\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis|amqp|mssql)://[^:@\s/]+:[^@\s]{3,}@",
        negate: Some(PLACEHOLDER_GUARD),
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(798),
        asvs: &["V2.10.4"],
        policy: &["SEC-03, b.3.1/1"],
    },

    Rule {
        id: "DB-CRY-001",
        category: Category::Cryptography,
        severity: Severity::Critical,
        title: "TLS Certificate Verification Disabled — Traffic Can Be Intercepted",
        description: "TLS certificate verification is switched off in application code.",
        impact: "An attacker on the network can read and modify all traffic. Encryption is present but the peer identity is never checked, so there is no actual protection.",
        remediation: "Restore verification. If a self-signed certificate is required, add its CA to the trust store instead.",
        pattern: r"(?i)verify\s*=\s*False|rejectUnauthorized\s*:\s*false|InsecureSkipVerify\s*:\s*true|NODE_TLS_REJECT_UNAUTHORIZED\s*[:=]\s*['\x22]?0|CURLOPT_SSL_VERIFYPEER\s*,\s*(?:0|false)|ServicePointManager\.ServerCertificateValidationCallback|trustAllCerts|ALLOW_ALL_HOSTNAME_VERIFIER|allowsAnyHTTPSCertificate",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(295),
        asvs: &["V9.2.1"],
        policy: &["CRYPTO-01, b.2/8"],
    },
    Rule {
        id: "DB-CRY-002",
        category: Category::Cryptography,
        severity: Severity::High,
        title: "Broken Hash Algorithm In Use (MD5/SHA-1)",
        description: "MD5 or SHA-1 is used for a security purpose.",
        impact: "Collisions are practical for both algorithms, which makes them unusable for signatures, integrity checks and password handling.",
        remediation: "Use SHA-256 or SHA-3. Passwords need Argon2id, scrypt or bcrypt, not a plain hash.",
        pattern: r"(?i)hashlib\.(?:md5|sha1)\s*\(|MessageDigest\.getInstance\s*\(\s*['\x22](?:MD5|SHA-?1)|createHash\s*\(\s*['\x22](?:md5|sha1)|md5\.New\(\)|sha1\.New\(\)|Digest::MD5|MD5\.Create\(\)",
        negate: Some(r"(?i)usedforsecurity\s*=\s*False|etag|checksum|cache[_-]?key|fingerprint|dedup|content[_-]?hash|gravatar"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(327),
        asvs: &["V6.2.2"],
        policy: &["CRYPTO-01, b.2/4"],
    },
    Rule {
        id: "DB-CRY-003",
        category: Category::Cryptography,
        severity: Severity::High,
        title: "Cipher Mode Cannot Detect Tampering (ECB/CBC)",
        description: "ECB mode, or CBC without a MAC, is used; legacy ciphers such as DES and RC4 also match.",
        impact: "Ciphertext can be modified without detection, and ECB leaks structure because identical blocks encrypt identically.",
        remediation: "Use an AEAD mode: AES-256-GCM or XChaCha20-Poly1305.",
        pattern: r"(?i)MODE_ECB|AES/ECB|AES/CBC/NoPadding|Cipher\.getInstance\s*\(\s*['\x22]AES['\x22]|(?-i:\bDESede\b|\bDESKeySpec\b|\bRC4\b|\b3?DES/|\bTripleDES\b)",
        negate: None,
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(327),
        asvs: &["V6.2.5"],
        policy: &["CRYPTO-01, b.2/3"],
    },
    Rule {
        id: "DB-CRY-004",
        category: Category::Cryptography,
        severity: Severity::Critical,
        title: "Password Stored With A Weak Function — No bcrypt Or argon2",
        description: "Passwords are processed with a plain hash function or with encryption.",
        impact: "If the database leaks, the passwords fall to GPU cracking within hours, and users are exposed on every other service where they reused them.",
        remediation: "Use Argon2id (m>=64 MiB, t>=3) or scrypt/bcrypt, with a unique salt per password.",
        pattern: r"(?i)(?:sha(?:1|256|512)|md5)\s*\([^)]*(?:password|passwd|pwd)|(?:password|passwd|pwd)[^\n=]{0,20}=\s*(?:hashlib|createHash|sha256|md5)|encrypt\s*\([^)]*password",
        negate: Some(r"(?i)argon|bcrypt|scrypt|pbkdf2"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(916),
        asvs: &["V2.4.1"],
        policy: &["CRYPTO-01, b.4.1"],
    },
    Rule {
        id: "DB-CRY-005",
        category: Category::Cryptography,
        severity: Severity::High,
        title: "Random Value Generated By A Predictable Source",
        description: "A predictable generator is used for a token, OTP, salt or identifier.",
        impact: "An attacker who recovers the generator state can compute future values — session hijacking, OTP prediction.",
        remediation: "Use a cryptographic generator: secrets (Python), crypto.randomBytes (Node), SecureRandom (Java/Kotlin), crypto/rand (Go).",
        pattern: r"(?i)(?:token|secret|password|passwd|otp|verification|nonce|salt|api_?key|session|csrf|uuid|reset_?code|invite|coupon|referral)\w*\s*(?:[:=]|\.\.\.)[^;\n]{0,80}(?:random\.(?:random|randint|choice|randrange|sample)|Math\.random|rand\.Intn|new\s+Random\(\)|mt_rand|arc4random_uniform)\s*\(|(?:random\.(?:randint|choice|randrange)|Math\.random|mt_rand)\s*\([^)]*\)[^;\n]{0,40}(?:token|otp|password|secret|nonce|salt)",
        negate: Some(r"(?i)jitter|backoff|shuffle|sample_data|mock|seed_data|animation|delay|colou?r|placeholder|demo|fixture|faker"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(338),
        asvs: &["V6.3.1"],
        policy: &["CRYPTO-01, b.5"],
    },
    Rule {
        id: "DB-CRY-006",
        category: Category::Cryptography,
        severity: Severity::High,
        title: "The Same IV Or Salt Is Reused On Every Encryption",
        description: "An IV, nonce or salt is defined as a constant in the code.",
        impact: "A repeated nonce under GCM allows key recovery, and a fixed salt makes rainbow-table attacks possible.",
        remediation: "Generate a fresh nonce or salt per operation with a cryptographic generator and store it alongside the ciphertext.",
        pattern: r#"(?i)\b(?:iv|nonce|salt)\s*[:=]\s*(?:b?["'][^"']{4,}["']|bytes\(|new\s+byte\s*\[)"#,
        negate: Some(r"(?i)urandom|randombytes|secrets\.|SecureRandom|crypto/rand|generate|token_bytes|\bos\.random"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(329),
        asvs: &["V6.2.7"],
        policy: &["CRYPTO-01, b.2/6"],
    },
    Rule {
        id: "DB-CRY-007",
        category: Category::Cryptography,
        severity: Severity::High,
        title: "JWT Signature Is Not Verified — Tokens Can Be Forged",
        description: "A JWT is decoded without verifying its signature, or without pinning the algorithm.",
        impact: "An attacker can mint a token with any contents — logging in as any user, in any role.",
        remediation: "Always verify the signature, pin the algorithm server-side (`none` is never accepted), and check `exp` and `aud`.",
        pattern: r#"(?i)verify_signature\s*[:=]\s*(?:False|false|0)|jwt\.decode\s*\(|jwt\.verify\s*\(|decode\s*\([^)]*complete\s*:\s*true|algorithms\s*[:=]\s*\[\s*['"]none"#,
        negate: Some(r#"(?i)algorithms\s*[:=]\s*\[\s*['"](?:HS|RS|ES|PS|Ed)|verify_signature\s*[:=]\s*True|options\s*=\s*\{[^}]*verify"#),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(347),
        asvs: &["V3.5.3"],
        policy: &["DEV-02, b.3.8"],
    },
    Rule {
        id: "DB-CRY-008",
        category: Category::Cryptography,
        severity: Severity::Medium,
        title: "Secret Compared With `==` — Discoverable By Timing",
        description: "A token, signature or HMAC is compared with an ordinary equality operator.",
        impact: "Differences in comparison time let an attacker recover the value character by character.",
        remediation: "Use hmac.compare_digest, crypto.timingSafeEqual or subtle.ConstantTimeCompare.",
        pattern: r"(?i)if\s+[\w\.\[\]]*(?:signature|hmac|token|digest|mac)[\w\.\[\]]*\s*==|==\s*[\w\.\[\]]*(?:signature|expected_hmac|expected_signature)",
        negate: Some(r"(?i)compare_digest|timingSafeEqual|ConstantTimeCompare|secure_compare|is\s+None|!=\s*None"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(208),
        asvs: &["V6.2.1"],
        policy: &["CRYPTO-01, b.5"],
    },

    Rule {
        id: "DB-INJ-001",
        category: Category::Injection,
        severity: Severity::Critical,
        title: "SQL Query Built By Pasting In User Input (SQL Injection)",
        description: "The query text is assembled with interpolation or concatenation.",
        impact: "SQL injection: the whole database can be read, modified or dropped, and authentication can be bypassed.",
        remediation: "Use parameterised queries or an ORM. User input never becomes part of the query text.",
        // Two properties this pattern has to hold at once.
        //
        // Each alternative excludes only its OWN delimiter: a class excluding both
        // quote characters missed the commonest shape there is —
        // f"... WHERE name = '{name}'" — because the apostrophe around the
        // placeholder ended the class before the placeholder was reached.
        //
        // And the verb is anchored to the start of the literal, because a query
        // begins with its verb while prose does not: f"could not DELETE record
        // '{rid}' from the archive" is an error message, not a query.
        pattern: r#"(?i)f"\s*(?:SELECT|INSERT|UPDATE|DELETE|REPLACE)\b[^"]*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN|TABLE)\b[^"]*\{|f"\s*(?:SELECT|INSERT|UPDATE|DELETE|REPLACE)\b[^"]*\{[^"]*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN|TABLE)\b|f'\s*(?:SELECT|INSERT|UPDATE|DELETE|REPLACE)\b[^']*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN|TABLE)\b[^']*\{|f'\s*(?:SELECT|INSERT|UPDATE|DELETE|REPLACE)\b[^']*\{[^']*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN|TABLE)\b|`\s*(?:SELECT|INSERT|UPDATE|DELETE)\b[^`]*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN)\b[^`]*\$\{|`\s*(?:SELECT|INSERT|UPDATE|DELETE)\b[^`]*\$\{[^`]*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN)\b|"\s*(?:SELECT|INSERT|UPDATE|DELETE)\b[^"]*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN)\b[^"]*"\s*(?:%|\+)\s*[\w(]|'\s*(?:SELECT|INSERT|UPDATE|DELETE)\b[^']*\b(?:FROM|INTO|WHERE|SET|VALUES|JOIN)\b[^']*'\s*(?:%|\+)\s*[\w(]|\.(?:execute|executemany|query|raw|prepare)\s*\(\s*[\w.]+\s*[%+]\s*[\w(]"#,
        negate: Some(r"(?i)\?\s*\)|:\w+\b|\$\d|%s\b|%\(\w+\)s|bindParam|prepared|text\(\s*[\x22']"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(89),
        asvs: &["V5.3.4"],
        policy: &["DEV-02, b.5.5"],
    },
    Rule {
        id: "DB-INJ-002",
        category: Category::Injection,
        severity: Severity::High,
        title: "System Command Assembled From A Variable (Command Injection)",
        description: "A shell command is built from variable content, or shell=True is used.",
        impact: "Command injection: arbitrary commands run on the server, which means full compromise.",
        remediation: "Call the binary with an argument list and no shell, and never concatenate user input into a command.",
        pattern: r"(?i)subprocess\.[a-z_]+\([^)]*shell\s*=\s*True|os\.system\s*\(|os\.popen\s*\(|child_process\.exec\s*\(|exec\.Command\s*\(\s*['\x22](?:sh|bash|cmd)|Runtime\.getRuntime\(\)\.exec|shell_exec\s*\(|passthru\s*\(|eval\s*\(\s*(?:f['\x22]|request|input|params)",
        negate: None,
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(78),
        asvs: &["V5.3.8"],
        policy: &["DEV-02, b.5.6"],
    },
    Rule {
        id: "DB-INJ-003",
        category: Category::Injection,
        severity: Severity::High,
        title: "Untrusted Data Deserialised Into Objects — Code Can Run",
        description: "Untrusted data is turned into objects (pickle, yaml.load, ObjectInputStream).",
        impact: "An attacker can execute code inside the process with a crafted payload.",
        remediation: "Use schema-based parsing only: yaml.safe_load, json, a Pydantic or serde model.",
        pattern: r"(?i)pickle\.loads?\s*\(|cPickle\.loads?\s*\(|yaml\.load\s*\(|marshal\.loads|ObjectInputStream|unserialize\s*\(|JSON\.parse\s*\(\s*(?:req|request)\.",
        negate: Some(r"(?i)SafeLoader|safe_load|CSafeLoader|BaseLoader|FullLoader"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(502),
        asvs: &["V5.5.1"],
        policy: &["DEV-02, b.5.7"],
    },
    Rule {
        id: "DB-INJ-004",
        category: Category::Injection,
        severity: Severity::High,
        title: "File Path Built From User Input — Other Files Can Be Read",
        description: "A file path is joined without validation, which allows path traversal.",
        impact: "An attacker can read or write system files with `../` — /etc/passwd or .env, for example.",
        remediation: "Canonicalise the path, verify it stays inside the allowed directory, and choose the file name yourself.",
        pattern: r#"(?i)(?:open|readFile|readFileSync|File\(|sendFile|serveFile|Path\()\s*\(\s*[^)]*(?:request\.|req\.|params\[|query\[|body\[|args\.get|GET\[|POST\[)"#,
        negate: Some(r"(?i)basename|secure_filename|realpath|canonical|resolve\(\)|sanitize"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(22),
        asvs: &["V12.3.1"],
        policy: &["DEV-02, b.5.8"],
    },
    Rule {
        id: "DB-INJ-005",
        category: Category::Frontend,
        severity: Severity::High,
        title: "User Text Injected Into The Page As HTML (XSS)",
        description: "Unescaped content is written through innerHTML, dangerouslySetInnerHTML, v-html or an equivalent.",
        impact: "Stored XSS: the attacker's script runs in other users' browsers, which means session theft and account takeover.",
        remediation: "Insert it as text (textContent or interpolation), or sanitise it with a library such as DOMPurify.",
        pattern: r"(?i)\.innerHTML\s*=|dangerouslySetInnerHTML|v-html\s*=|\[innerHTML\]|document\.write\s*\(|\.html\s*\(\s*(?:[a-z_$][\w$]*\.|`)",
        negate: Some(r"(?i)DOMPurify|sanitize|escapeHtml|createTextNode"),
        languages: &[],
        scope: Scope::Frontend,
        skip_tests: true,
        cwe: Some(79),
        asvs: &["V5.3.3"],
        policy: &["DEV-02, b.8.1"],
    },
    Rule {
        id: "DB-INJ-006",
        category: Category::Injection,
        severity: Severity::Medium,
        title: "Server Fetches A User-Supplied URL (SSRF) — Internal Network Exposed",
        description: "The target of an outbound request is derived from user input.",
        impact: "An attacker can reach internal services and the cloud metadata endpoint, and obtain credentials from it.",
        remediation: "Restrict the target with an allowlist, block internal ranges, and do not follow redirects.",
        pattern: r"(?i)(?:requests\.(?:get|post)|httpx\.(?:get|post)|fetch|axios\.(?:get|post)|urlopen|http\.Get|HttpClient)\s*\(\s*[^)]*(?:request\.|req\.|params\[|query\[|body\[|args\.get|url\s*=\s*user)",
        negate: Some(r"(?i)allowlist|allowed_hosts|whitelist|urlparse.*netloc.*in\s"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(918),
        asvs: &["V12.6.1"],
        policy: &["DEV-02, b.6.1"],
    },

    Rule {
        id: "DB-AUZ-001",
        category: Category::Authorization,
        severity: Severity::Medium,
        title: "Authorisation Decided Only In The Frontend — Trivially Bypassed",
        description: "A role or permission check is performed in interface code only.",
        impact: "The user bypasses it entirely by calling the API directly. Hiding a button is not a control.",
        remediation: "Keep this check for presentation only; the real decision belongs on the server, at every endpoint.",
        pattern: r"(?i)if\s*\(?\s*(?:user|currentUser|me|profile|auth)\??\.(?:isAdmin|is_admin|role|roles|isStaff|is_staff|permissions?)\s*(?:[=!]==?|\.includes|\.contains)",
        negate: None,
        languages: &[],
        scope: Scope::Frontend,
        skip_tests: true,
        cwe: Some(602),
        asvs: &["V4.1.1"],
        policy: &["DEV-02, b.4.3"],
    },
    Rule {
        id: "DB-AUZ-002",
        category: Category::Authorization,
        severity: Severity::Medium,
        title: "Identifiers Are Sequential — Other People's Data Can Be Guessed",
        description: "A sequential integer identifier is used as a route parameter.",
        impact: "An attacker can enumerate other users' objects by changing the identifier (IDOR plus enumeration).",
        remediation: "Use a random external identifier such as a UUID, and verify ownership on every request.",
        pattern: r"(?i)(?:@(?:app|router|blueprint)\.(?:get|post|put|patch|delete)|path|route|Get|Post)\s*\(\s*['\x22][^'\x22]*[<{:]\s*(?:int\s*:\s*)?(?:id|pk|user_id|order_id|account_id)\s*[>}]",
        negate: None,
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(639),
        asvs: &["V4.2.1"],
        policy: &["DEV-02, b.4.7"],
    },
    Rule {
        id: "DB-AUN-001",
        category: Category::Authentication,
        severity: Severity::High,
        title: "Endpoint Is Open Without An Authentication Check",
        description: "The endpoint explicitly disables its authentication requirement.",
        impact: "Functionality that should be protected is exposed to anonymous callers.",
        remediation: "Apply deny-by-default and document why any exception is necessary.",
        pattern: r"(?i)@?(?:permission_classes\s*=\s*\[\s*AllowAny|AllowAny|@csrf_exempt|@login_not_required|authentication_classes\s*=\s*\[\s*\]|\[AllowAnonymous\]|auth\s*:\s*false|requireAuth\s*:\s*false)",
        negate: None,
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(306),
        asvs: &["V4.1.3"],
        policy: &["DEV-02, b.4.1"],
    },
    Rule {
        id: "DB-AUN-002",
        category: Category::Authentication,
        severity: Severity::Medium,
        title: "Session Cookie Set Without HttpOnly Or Secure",
        description: "The cookie explicitly disables HttpOnly, Secure or SameSite.",
        impact: "Script can read the cookie, which turns an XSS into session theft, or the cookie travels over an unencrypted channel.",
        remediation: "Set HttpOnly, Secure and SameSite=Lax or Strict.",
        pattern: r"(?i)(?:httponly|http_only)\s*[:=]\s*(?:False|false|0)|secure\s*[:=]\s*(?:False|false)\s*[,)]|samesite\s*[:=]\s*['\x22]?none",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(1004),
        asvs: &["V3.4.1"],
        policy: &["DEV-02, b.8.5"],
    },

    Rule {
        id: "DB-DAT-001",
        category: Category::DataProtection,
        severity: Severity::High,
        title: "Sensitive Data Written To The Log (Password, Token, Card)",
        description: "A password, token, card number or personal data is passed to a log or analytics call.",
        impact: "Logs are usually accessible to a wider audience and retained for a long time, and they are rarely encrypted.",
        remediation: "Mask the field or drop it entirely, and install a central masking filter.",
        pattern: r"(?i)(?:log(?:ger|ging)?\.(?:debug|info|warn|warning|error|critical)|print|println|console\.(?:log|info|warn|error)|System\.out\.print|NSLog|Timber\.|capture_message|track|analytics\.\w+)\s*\([^)]*\b(?:password|passwd|token|secret|api_?key|authorization|cookie|session_id|card|pan|cvv|iban|ssn|fin|passport|email|phone)\b",
        negate: Some(r"(?i)masked|redact|\*{3,}|hidden|len\(|length|is_set|exists|bool\(|has_"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(532),
        asvs: &["V7.1.1"],
        policy: &["DEV-02, b.9.4", "SEC-05, b.3"],
    },
    Rule {
        id: "DB-DAT-002",
        category: Category::ErrorHandling,
        severity: Severity::Medium,
        title: "Internal Error Text Returned To The User — Internals Exposed",
        description: "A stack trace or the text of an error object is included in the response.",
        impact: "An attacker learns the technology, versions, file paths and query structure.",
        remediation: "Return a generic message with a correlation id, and keep the detail in the server log.",
        pattern: r"(?i)(?:return|res\.(?:send|json)|jsonify|JsonResponse|HttpResponse)\s*\([^)]*(?:traceback\.format_exc|str\(e\)|e\.stack|exception\.getMessage|err\.message|\{\s*['\x22]error['\x22]\s*:\s*(?:str\(|e\b))",
        negate: None,
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(209),
        asvs: &["V7.4.1"],
        policy: &["DEV-02, b.9.2"],
    },
    Rule {
        id: "DB-DAT-003",
        category: Category::ErrorHandling,
        severity: Severity::High,
        title: "Error Caught But Never Recorded — The Failure Stays Hidden",
        description: "The exception is caught but neither logged nor propagated.",
        impact: "The failure is hidden: the system carries on in a wrong state, the incident is never noticed and diagnosis is impossible.",
        remediation: "Log the error or propagate it. If it is swallowed deliberately, state the reason in a comment.",
        pattern: r"(?i)except[^\n:]*:\s*pass\s*$|except\s*:\s*$|catch\s*\([^)]*\)\s*\{\s*\}|\.catch\s*\(\s*\(\s*\)\s*=>\s*\{?\s*\}?\s*\)|rescue\s*(?:=>\s*\w+)?\s*$|catch\s*\{\s*\}|if\s+err\s*!=\s*nil\s*\{\s*\}",
        negate: None,
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(390),
        asvs: &["V7.4.3"],
        policy: &["DEV-02, b.9.1"],
    },
    Rule {
        id: "DB-PRV-001",
        category: Category::Privacy,
        severity: Severity::Medium,
        title: "Third-Party Analytics SDK Sends User Behaviour Outside",
        description: "A component that reports user behaviour to an external service was detected.",
        impact: "Transferring personal data to a third party requires a legal basis, disclosure in the privacy policy and a consent mechanism.",
        remediation: "Document the fields collected, add them to the privacy policy, implement consent, and anonymise where possible.",
        pattern: r"(?i)(?:google-analytics|googletagmanager|gtag\(|firebase/analytics|FirebaseAnalytics|mixpanel|amplitude|segment\.com|analytics\.identify|posthog|hotjar|fullstory|smartlook|clarity\.ms|appsflyer|adjust\.com|facebook\.com/tr|fbq\(|sentry.*sendDefaultPii\s*[:=]\s*true)",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(359),
        asvs: &["V8.3.1"],
        policy: &["SEC-05, b.4"],
    },
    Rule {
        id: "DB-PRV-002",
        category: Category::Privacy,
        severity: Severity::High,
        title: "Personal Data Stored Unencrypted On The Device",
        description: "A sensitive value is kept in ordinary local storage instead of the platform secure store.",
        impact: "The data is readable once the device is compromised, or through a backup, and it lands in iOS and Android backups.",
        remediation: "Use Keychain (iOS), Keystore with EncryptedSharedPreferences (Android), or an encrypted local database.",
        pattern: r"(?i)(?:localStorage|sessionStorage|AsyncStorage|SharedPreferences|UserDefaults|shared_preferences)\s*(?:\.setItem\s*\(|\.set\w*\s*\(|\[)\s*['\x22][^'\x22]*(?:token|password|secret|pin|card|auth|credential|refresh)",
        negate: Some(r"(?i)EncryptedSharedPreferences|Keychain|SecureStore|flutter_secure_storage|keystore"),
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(922),
        asvs: &["V8.2.2"],
        policy: &["DEV-02, b.13.2"],
    },

    Rule {
        id: "DB-CFG-001",
        category: Category::Configuration,
        severity: Severity::High,
        title: "CORS Allows Requests From Any Site (`*`)",
        description: "Every origin is allowed, and credentials are permitted alongside.",
        impact: "Any site can call your API with the user's session and read the response.",
        remediation: "Define an explicit allowlist. `*` is never combined with `credentials: true`.",
        pattern: r#"(?i)allow_origins\s*=\s*\[\s*["']\*["']|Access-Control-Allow-Origin["']?\s*[:,]\s*["']\*|origin\s*:\s*["']\*["']|AllowedOrigins.*\*|cors\(\s*\)"#,
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(942),
        asvs: &["V14.5.3"],
        policy: &["DEV-02, b.8.4"],
    },
    Rule {
        id: "DB-CFG-002",
        category: Category::Configuration,
        severity: Severity::High,
        title: "Debug Mode May Be Left On In Production",
        description: "Debug mode is hardcoded as enabled.",
        impact: "Debug pages expose internal state, configuration and sometimes secrets, and in some frameworks they allow code execution.",
        remediation: "Read debug mode from an environment variable and keep it off in production.",
        pattern: r"(?i)DEBUG\s*[:=]\s*True|APP_DEBUG\s*=\s*true|FLASK_DEBUG\s*=\s*1|app\.run\([^)]*debug\s*=\s*True|NODE_ENV\s*[:=]\s*['\x22]development['\x22]",
        negate: Some(r"(?i)os\.environ|getenv|process\.env|\.example|settings/dev|local\.py|dev\.toml"),
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(489),
        asvs: &["V14.1.3"],
        policy: &["DEV-02, b.9.2"],
    },
    Rule {
        id: "DB-CFG-003",
        category: Category::ApiContract,
        severity: Severity::Medium,
        title: "Query Fetches Every Row — No Pagination (LIMIT)",
        description: "A query returns all rows with no limit.",
        impact: "As the data grows, the query blocks the database and the application — a denial-of-service risk — and it makes bulk extraction easy.",
        remediation: "Enforce pagination with a maximum page size.",
        pattern: r"(?i)(?:\.objects\.all\(\)|\.findAll\s*\(\s*\)|SELECT\s+\*\s+FROM\s+\w+\s*(?:;|$)|\.find\s*\(\s*\{\s*\}\s*\)|\.scan\s*\(\s*\))",
        negate: Some(r"(?i)limit|\[:\d+\]|paginate|page_size|take\(|first\(|count\(|exists\(|\.only\(|values_list"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(770),
        asvs: &["V13.4.2"],
        policy: &["DEV-02, b.10.5"],
    },
    Rule {
        id: "DB-CFG-004",
        category: Category::ApiContract,
        severity: Severity::Low,
        title: "Outbound Request Has No Timeout — The System Can Hang",
        description: "An HTTP request is issued without a timeout.",
        impact: "If the remote service stops answering, the request waits indefinitely, worker processes are exhausted and the whole service stalls.",
        remediation: "Set a timeout on every outbound call, plus a retry policy and a circuit breaker.",
        pattern: r"(?i)(?:requests\.(?:get|post|put|patch|delete)|httpx\.(?:get|post)|urlopen|http\.(?:Get|Post))\s*\(",
        negate: Some(r"(?i)timeout|deadline|context\.With|AbortController|signal"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(1088),
        asvs: &["V13.2.6"],
        policy: &["DEV-02, b.6.3"],
    },

    Rule {
        id: "DB-MIG-001",
        category: Category::Database,
        severity: Severity::Critical,
        title: "Migration Deletes Data With No Condition",
        description: "TRUNCATE, or DELETE/UPDATE without a WHERE clause.",
        impact: "One migration run empties the whole table, and only a backup can bring it back.",
        remediation: "Add a condition, split the operation into steps, and confirm a backup exists before running it.",
        pattern: r"(?i)\bTRUNCATE\b|\b(?:DELETE\s+FROM|UPDATE)\s+[\w\x22.`]+\s*(?:;|$)",
        negate: Some(r"(?i)\bWHERE\b"),
        languages: &[],
        scope: Scope::Migration,
        skip_tests: false,
        cwe: Some(1088),
        asvs: &[],
        policy: &["DEV-04, b.6.4/2", "DEV-04, b.6.4/3"],
    },
    Rule {
        id: "DB-MIG-002",
        category: Category::Database,
        severity: Severity::High,
        title: "Migration Drops Or Renames A Column — Older Code Breaks Immediately",
        description: "The schema change happens in a single step, which breaks the expand-contract rule.",
        impact: "Older mobile versions on user devices keep querying the old schema and start failing. A mobile release cannot be rolled back, so the damage is irreversible.",
        remediation: "Five steps: add, write to both, backfill, switch reads, then drop the old column in a SEPARATE release.",
        pattern: r"(?i)DROP\s+(?:TABLE|COLUMN)|drop_table|drop_column|RENAME\s+COLUMN|new_column_name|ALTER\s+COLUMN\s+\w+\s+TYPE",
        negate: None,
        languages: &[],
        scope: Scope::Migration,
        skip_tests: false,
        cwe: None,
        asvs: &[],
        policy: &["DEV-04, b.6.2"],
    },
    Rule {
        id: "DB-MIG-003",
        category: Category::Database,
        severity: Severity::Medium,
        title: "Index Created While Locking The Table — Writes Stop In Production",
        description: "CREATE INDEX runs without CONCURRENTLY.",
        impact: "On a large table the operation locks it, which effectively takes the service down during deployment.",
        remediation: "Use CONCURRENTLY and run the migration as a separate, non-transactional step.",
        pattern: r"(?i)CREATE\s+(?:UNIQUE\s+)?INDEX",
        negate: Some(r"(?i)CONCURRENTLY|postgresql_concurrently|IF\s+NOT\s+EXISTS.*CONCURRENTLY"),
        languages: &[],
        scope: Scope::Migration,
        skip_tests: false,
        cwe: None,
        asvs: &[],
        policy: &["DEV-04, b.6.4/5"],
    },
    Rule {
        id: "DB-MIG-004",
        category: Category::Database,
        severity: Severity::Medium,
        title: "NOT NULL Column Added Without A Default — The Migration Fails",
        description: "A mandatory column is added without a value for existing rows.",
        impact: "The migration aborts on a non-empty table and the deployment is left half-applied.",
        remediation: "Add it as nullable first, backfill existing rows, then apply NOT NULL.",
        pattern: r"(?i)ADD\s+COLUMN\s+[\w\x22]+\s+[\w()]+\s+NOT\s+NULL|nullable\s*=\s*False",
        negate: Some(r"(?i)DEFAULT|server_default"),
        languages: &[],
        scope: Scope::Migration,
        skip_tests: false,
        cwe: None,
        asvs: &[],
        policy: &["DEV-04, b.6.2"],
    },

    Rule {
        id: "DB-INF-001",
        category: Category::Infrastructure,
        severity: Severity::Medium,
        title: "Container Runs As Root",
        description: "The Dockerfile has no USER instruction, or sets root.",
        impact: "An attacker who achieves code execution in the application is root inside the container, which raises the risk of container escape.",
        remediation: "Create an unprivileged user and set `USER appuser`.",
        pattern: r"(?i)^\s*USER\s+root\s*$",
        negate: None,
        languages: &["Docker"],
        scope: Scope::Infra,
        skip_tests: false,
        cwe: Some(250),
        asvs: &["V14.1.6"],
        policy: &[],
    },
    Rule {
        id: "DB-INF-002",
        category: Category::Infrastructure,
        severity: Severity::High,
        title: "Service Binds To 0.0.0.0 — Reachable From Outside",
        description: "A database or internal service listens on 0.0.0.0.",
        impact: "The service may be reachable from the public internet, which for a database is a direct data-leak path.",
        remediation: "Bind to an internal interface (127.0.0.1 or a private network) and restrict it at the network layer.",
        pattern: r#"(?i)(?:ports?\s*:\s*[\s\-\x22']*|\-p\s+)0\.0\.0\.0:(?:5432|3306|27017|6379|9200|11211|5984)|listen_addresses\s*=\s*['\x22]?\*"#,
        negate: None,
        languages: &[],
        scope: Scope::Infra,
        skip_tests: false,
        cwe: Some(668),
        asvs: &["V1.14.6"],
        policy: &["SEC-01, b.9/3"],
    },
    Rule {
        id: "DB-INF-003",
        category: Category::Infrastructure,
        severity: Severity::High,
        title: "Password Or Key Hardcoded In Infrastructure Configuration",
        description: "A cleartext password or key in a Docker Compose file, Kubernetes manifest or Terraform file.",
        impact: "Configuration files usually live in the repository and are visible to a wide audience.",
        remediation: "Use a secret manager (Kubernetes Secrets with encryption, SOPS, a vault) and rotate the value.",
        pattern: r#"(?i)(?:POSTGRES_PASSWORD|MYSQL_ROOT_PASSWORD|MONGO_INITDB_ROOT_PASSWORD|REDIS_PASSWORD|SECRET_KEY|API_KEY|ADMIN_PASSWORD)\s*[:=]\s*["']?[^\s"'$\{]{6,}"#,
        negate: Some(PLACEHOLDER_GUARD),
        languages: &[],
        scope: Scope::Infra,
        skip_tests: false,
        cwe: Some(798),
        asvs: &["V14.1.4"],
        policy: &["SEC-03, b.3.1/1"],
    },
    Rule {
        id: "DB-INF-004",
        category: Category::Infrastructure,
        severity: Severity::Medium,
        title: "Unencrypted `http://` Endpoint In Use",
        description: "An external address is used with the http:// scheme in configuration or code.",
        impact: "Traffic is unencrypted: credentials and data cross the network in the clear and can be modified.",
        remediation: "Use https:// and keep HTTP only for redirecting to it.",
        pattern: r"http://[a-z0-9\-]+(?:\.[a-z0-9\-]+)+",
        negate: Some(
            r"(?i)localhost|127\.0\.0\.1|0\.0\.0\.0|host\.docker|\.local\b|\.internal\b|\.svc\b|\
             example\.(?:com|org|net)|w3\.org|schemas\.|xmlns|schemaLocation|DOCTYPE|\
             redirect|upgrade-insecure|purl\.org|\{\{|\$\{|<[a-z_]+>|test|mock|localstack|minio",
        ),
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(319),
        asvs: &["V9.1.1"],
        policy: &["CRYPTO-01, b.3.1"],
    },
    Rule {
        id: "DB-SUP-001",
        category: Category::SupplyChain,
        severity: Severity::Medium,
        title: "CI Step Pinned To A Mutable Tag — The Code Can Change Silently",
        description: "A GitHub Action or container image is referenced by a mutable tag instead of a version or commit.",
        impact: "The owner of the component can change its contents at any time, and a compromised tag runs code inside your CI environment.",
        remediation: "Pin actions to a commit hash and container images to a digest.",
        pattern: r"(?i)uses\s*:\s*[\w\-\./]+@(?:main|master|v\d+|latest)\s*$|FROM\s+[\w\-\./]+:latest",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(1357),
        asvs: &["V14.2.4"],
        policy: &["DEV-03, b.6.4"],
    },
    Rule {
        id: "DB-TST-001",
        category: Category::Compliance,
        severity: Severity::Medium,
        title: "Test Is Disabled (skip) — It Verifies Nothing",
        description: "The test is deactivated with skip, xfail or only.",
        impact: "A disabled test masks a regression: the pipeline is green while that behaviour is no longer checked. Temporary disabling becomes permanent in practice.",
        remediation: "Either fix the test or delete it. If it must stay, state the reason and the return date in a comment.",
        pattern: r"(?i)@pytest\.mark\.(?:skip|xfail)|@unittest\.skip|\bit\.skip\s*\(|\bdescribe\.skip\s*\(|\bxit\s*\(|\bxdescribe\s*\(|\btest\.skip\s*\(|#\[ignore\]|@Ignore\b|\bt\.Skip\s*\(",
        negate: Some(r"(?i)reason\s*=\s*['\x22][^'\x22]{10,}|until=|TODO\(#\d+\)"),
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: None,
        asvs: &[],
        policy: &["DEV-01, b.9"],
    },
    Rule {
        id: "DB-TST-002",
        category: Category::Compliance,
        severity: Severity::High,
        title: "`.only` Left In Place — Every Other Test Is Skipped",
        description: "`.only`, `fdescribe` or `fit` is in use.",
        impact: "The pipeline runs a single test and reports green, silently skipping the entire suite. This is the most dangerous test defect to commit by accident.",
        remediation: "Remove the `.only`, `fdescribe` or `fit` call and use a CLI filter for local focus.",
        pattern: r"(?i)\b(?:it|describe|test|context)\.only\s*\(|\bfdescribe\s*\(|\bfit\s*\(",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: None,
        asvs: &[],
        policy: &["DEV-01, b.9"],
    },

    Rule {
        id: "DB-MOB-001",
        category: Category::Mobile,
        severity: Severity::High,
        title: "Mobile App Permits Unencrypted HTTP",
        description: "An iOS ATS exception or Android cleartext permission is enabled.",
        impact: "The app can open unencrypted connections, so traffic on public Wi-Fi is readable and modifiable. One exception can open an entire domain.",
        remediation: "Disable NSAllowsArbitraryLoads and cleartextTrafficPermitted, and write a narrow exception for the domains that genuinely need one.",
        pattern: r"(?i)NSAllowsArbitraryLoads\s*</key>\s*<true|NSAllowsArbitraryLoads\W+true|android:usesCleartextTraffic\s*=\s*\x22true|cleartextTrafficPermitted\s*=\s*\x22true",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(319),
        asvs: &["V9.1.1"],
        policy: &["CRYPTO-01, b.3.4"],
    },
    Rule {
        id: "DB-MOB-002",
        category: Category::Mobile,
        severity: Severity::High,
        title: "Android App Is Debuggable Or Allows Backup",
        description: "`android:debuggable=\"true\"` or `android:allowBackup=\"true\"`.",
        impact: "debuggable: anyone can attach to the process on the device and read memory. allowBackup: adb extracts all local app data, tokens and personal data included.",
        remediation: "Set both to `false`. If backup is required, use encrypted, selective backup rules.",
        pattern: r"(?i)android:debuggable\s*=\s*\x22true|android:allowBackup\s*=\s*\x22true",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(922),
        asvs: &["V8.2.2"],
        policy: &["DEV-02, b.13"],
    },
    Rule {
        id: "DB-MOB-003",
        category: Category::Mobile,
        severity: Severity::High,
        title: "WebView Exposes A JavaScript Bridge Or File Access",
        description: "`addJavascriptInterface`, `setAllowFileAccess(true)` or a weakly configured `setJavaScriptEnabled`.",
        impact: "Script running in the WebView can call native code or read local files, so one XSS turns into access to on-device data.",
        remediation: "Remove the bridge or restrict it to trusted origins, disable file access, and load allowlisted URLs only.",
        pattern: r"(?i)addJavascriptInterface\s*\(|setAllowFileAccess(?:FromFileURLs)?\s*\(\s*true|setAllowUniversalAccessFromFileURLs\s*\(\s*true|allowFileAccessFromFileURLs\s*:\s*true",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(749),
        asvs: &[],
        policy: &["DEV-02, b.13"],
    },
    Rule {
        id: "DB-MOB-004",
        category: Category::Mobile,
        severity: Severity::Medium,
        title: "Android Component Exported Without A Permission",
        description: "`android:exported=\"true\"` without a matching `android:permission`.",
        impact: "Any app on the device can invoke this component: unauthorised operations, data reads or intent manipulation.",
        remediation: "Set `exported=\"false\"`, or add a signature-level `android:permission`.",
        pattern: r"(?i)android:exported\s*=\s*\x22true",
        negate: Some(r"(?i)android:permission|LAUNCHER|android\.intent\.action\.MAIN"),
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(926),
        asvs: &[],
        policy: &["DEV-02, b.13"],
    },

    Rule {
        id: "DB-CI-001",
        category: Category::Secrets,
        severity: Severity::High,
        title: "Secret Can Reach The CI Log",
        description: "A secret variable is printed with `echo` or `print`, or `set -x` is active.",
        impact: "CI logs are usually visible to a wider audience and retained for a long time, and sometimes they are publicly downloadable. A secret that reaches a log counts as leaked and must be rotated.",
        remediation: "Remove the print. If you need it for debugging, mask the value, and close a `set -x` block with `set +x` before the secret is used.",
        pattern: r"(?i)echo\s+[^\n]*\$\{?\s*(?:[A-Z_]*(?:SECRET|TOKEN|PASSWORD|KEY|CREDENTIAL)[A-Z_]*)|print\s*\(\s*os\.environ\s*\)|set\s+-x",
        negate: Some(r"(?i)set\s+\+x|MASK|\*{3,}|::add-mask::"),
        languages: &[],
        scope: Scope::Any,
        skip_tests: true,
        cwe: Some(532),
        asvs: &["V7.1.1"],
        policy: &["DEV-03, b.6.7"],
    },
    Rule {
        id: "DB-CI-002",
        category: Category::Infrastructure,
        severity: Severity::Critical,
        title: "CI Workflow Hands Secrets To Code From A Fork",
        description: "Secrets are used under a `pull_request_target` or `workflow_run` trigger.",
        impact: "These triggers run a pull request from a fork with the BASE repository's secrets. An attacker opens a pull request and the workflow runs their code with your keys — a classic CI compromise.",
        remediation: "Move to the `pull_request` trigger. If `pull_request_target` is unavoidable, check out the BASE ref and never execute fork code.",
        pattern: r"(?i)pull_request_target|workflow_run",
        negate: None,
        languages: &[],
        scope: Scope::Any,
        skip_tests: false,
        cwe: Some(1357),
        asvs: &["V14.2.4"],
        policy: &["DEV-03, b.6.3"],
    },

    Rule {
        id: "DB-SEC-005",
        category: Category::Secrets,
        severity: Severity::High,
        title: "Long Random-Looking Constant — Possibly A Secret",
        description: "A long, random-looking string is defined as a constant. Pattern matching only catches KNOWN formats, so this rule targets internal token formats.",
        impact: "If this is a key or a token, everyone with repository access obtains it, and removing it from git history is not practical.",
        remediation: "Check the value: if it is a secret, move it to configuration and rotate it. If it is not (a hash, test vector or identifier), append `# deadbolt-ignore DB-SEC-005 until=... reason=...` to the line.",
        pattern: r#"[:=]\s*["'][A-Za-z0-9+/=_\-]{28,}["']"#,
        negate: Some(r"(?i)https?://|base64|sha256|sha512|md5|checksum|integrity|sri|lock|hash|digest|uuid|snapshot|fixture|example|test|mock|public[_-]?key|BEGIN|\.(?:png|jpg|svg|woff)|data:"),
        languages: &[],
        scope: Scope::Code,
        skip_tests: true,
        cwe: Some(798),
        asvs: &["V2.10.4"],
        policy: &["SEC-03, b.3.1/1"],
    },
];
