//! The vocabulary each AI lens looks for.
//!
//! This file is data, not logic. It lives apart from `prompt.rs` for the same
//! reason `scan/catalog.rs` lives apart from the scanner: it necessarily *contains*
//! the very strings the engine hunts for — `pull_request_target`, `mixpanel`,
//! `card_number` — so scanning it reports the tool's own vocabulary as the tool's
//! own defects. Keeping the list here means `prompt.rs` stays ordinary code that
//! an audit can read, and only this file has to be excluded.
//!
//! A marker earns its place by being cheap and specific: present in files where
//! the lens has something to say, absent in files where it does not.

pub const AUTHZ: &[&str] = &[
    "@app.",
    "@router.",
    "router.",
    "app.get(",
    "app.post(",
    "@GetMapping",
    "@PostMapping",
    "current_user",
    "request.user",
    "get_object_or_404",
    "findOrFail",
    "is_admin",
    "is_staff",
    "hasRole",
    "permission",
    "tenant_id",
    "owner_id",
    "setattr",
    "Object.assign",
    "**request",
];

pub const DATA: &[&str] = &[
    "log",
    "logger",
    "print(",
    "console.",
    "Timber",
    "capture",
    "track(",
    "analytics",
    "gtag",
    "mixpanel",
    "amplitude",
    "posthog",
    "serializer",
    "to_dict",
    "toJSON",
    "response_model",
    "__all__",
    "model_dump",
    "national_id",
    "passport",
    "iban",
    "card_number",
    "cvv",
    "phone",
    "birth",
];

pub const FAILURE: &[&str] = &[
    "except",
    "catch",
    "rescue",
    "err != nil",
    "timeout",
    "retry",
    "circuit",
    "idempot",
    "commit(",
    "transaction",
    "atomic",
    "queue",
    "celery",
    "sidekiq",
    "kafka",
    "rabbitmq",
    "ratelimit",
    "throttle",
    "limiter",
];

pub const CRYPTO: &[&str] = &[
    "encrypt",
    "decrypt",
    "cipher",
    "AES",
    "GCM",
    "ChaCha",
    "hmac",
    "hashlib",
    "bcrypt",
    "argon",
    "scrypt",
    "jwt",
    "sign(",
    "verify(",
    "secret_key",
    "private_key",
    "nonce",
    "iv =",
    "random",
    "urandom",
    "SecureRandom",
    "token",
];

pub const MIGRATION: &[&str] = &[
    "drop_column",
    "DROP COLUMN",
    "drop_table",
    "DROP TABLE",
    "rename_column",
    "RENAME COLUMN",
    "alter_column",
    "ALTER COLUMN",
    "ADD COLUMN",
    "CREATE INDEX",
    "TRUNCATE",
    "DELETE FROM",
    "downgrade",
    "def down",
    "op.execute",
];

pub const API: &[&str] = &[
    "@app.",
    "@router.",
    "router.",
    "request.json",
    "request.body",
    "req.body",
    "limit",
    "per_page",
    "page_size",
    "upload",
    "multipart",
    "FileField",
    "webhook",
    "signature",
    "graphql",
    "resolver",
    "schema",
    "serializer",
    "dto",
];

pub const FRONTEND: &[&str] = &[
    "innerHTML",
    "dangerouslySetInnerHTML",
    "v-html",
    "document.write",
    "insertAdjacentHTML",
    "localStorage",
    "sessionStorage",
    "AsyncStorage",
    "NEXT_PUBLIC_",
    "VITE_",
    "EXPO_PUBLIC_",
    "REACT_APP_",
    "location.href",
    "router.push",
    "window.open",
    "WebView",
    "JavascriptInterface",
    "eval(",
    "new Function(",
];

pub const INFRA: &[&str] = &[
    "0.0.0.0",
    "ports:",
    "EXPOSE",
    "USER ",
    "privileged",
    "CAP_",
    "securityContext",
    "runAsUser",
    "docker.sock",
    "PASSWORD",
    "SECRET",
    "TOKEN",
    "pull_request_target",
    "workflow_run",
    "uses:",
    "image:",
    "ssl_protocols",
    "listen 80",
    "backup",
    "retention",
    "object-lock",
];
